# Generated by Django 5.1.6 on 2025-03-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_business_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
