# Generated by Django 5.1.6 on 2025-03-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_info', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('business_images', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media', models.URLField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('both', 'Both')], max_length=10)),
                ('additional_services', models.JSONField(blank=True, null=True)),
                ('business_reg_no', models.CharField(max_length=50, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
