# Generated by Django 5.1.6 on 2025-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='additional_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
