# Generated by Django 5.1.6 on 2025-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_additional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_reg_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
