# Generated by Django 5.1.6 on 2025-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
